[review]
allow-users = [
  "nolouch",
  "HunDunDM",
  "rleungx",
  "disksing",
  "JmPotato",
  "lhy1024",
  "AndreMouche",
  "bufferflies",
  "CabinfeverB",
  "Yisaer",
]
block-comments = [
  "/run-",
  "/merge",
  "/rebuild",
]
block-labels = [
  "cherry-pick-approved",
  "status/can-merge",
]
block-users = [
  "sre-bot",
  "ti-chi-bot",
  "ti-srebot",
  "codecov",
  "codecov[bot]",
  "codecov-commenter",
  "CLAassistant",
  "hound[bot]",
]
lgtm-comments = [
  "/lgtm",
  "LGTM",
]

# Could also be set with the environment variable:
#   - GHSTATS_GITHUB_TOKEN
#   - GHSTATS_FEISHU_WEBHOOK_TOKEN
[review.access]
feishu-webhook-token = ""
github-token = ""

[[review.repos]]
name = "PD"
pr-query = [
  # Open PD PR and issues in tikv/pd repo.
  """
repo:tikv/pd
""",
  """
repo:tikv/client-go
""",
  """
repo:tikv/tikv
""",
  """
repo:pingcap/tidb
""",
]

# [ptal]
# [ptal.access]
# github-token = "<TOKEN>"
# # Test bot
# feishu-webhook-token = "<TOKEN>"

# [[ptal.repos]]
# name = "PD"
# pr-query = [
#   # Open PR in tikv/pd repo.
#   # Excludes PRs that not ready.
#   # Excludes PRs that ready to merge.
#   # Excludes cherry-pick PRs.
#   """
# repo:tikv/pd type:pr state:open \
# draft:false -label:do-not-merge/work-in-progress -label:do-not-merge/hold \
# -label:status/LGT2 -label:status/can-merge \
# -label:type/cherry-pick-for-release-5.0 -label:type/cherry-pick-for-release-4.0 \
# sort:created-desc
# """,
# ]
