name: Daily Github Review Stats of Scheduling Team

on:
  schedule:
    # UTC+8 18:00 on every day-of-week from Monday to Thursday.
    - cron: "0 10 * * 1-4"
  workflow_dispatch:

jobs:
  review-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.21.0"
      - run: |
          make run-daily-check-test
        env:
          GHSTATS_GITHUB_TOKEN: ${{ secrets.GHSTATS_GITHUB_TOKEN }}
          GHSTATS_FEISHU_WEBHOOK_TOKEN: ${{ secrets.GHSTATS_FEISHU_WEBHOOK_TOKEN }}
